"""The decisions folder's INDEX.md (ADR0013V01R01): regenerated by every
command that writes a decision, never taken for a decision itself."""
import json

import pytest

from adrpy.cli import approve, check, explore, init, new
from adrpy.core.config import load_repo_config


def _repo(tmp_path):
    init.run(["--path", str(tmp_path)])
    return tmp_path, tmp_path / "doc" / "adr" / "INDEX.md"


def test_init_writes_an_index_with_no_decisions(tmp_path):
    _, index = _repo(tmp_path)
    text = index.read_text(encoding="utf-8")
    assert text.startswith("# ")
    assert "ADR0" not in text


def test_new_and_approve_keep_the_index_in_step(tmp_path):
    root, index = _repo(tmp_path)
    created = new.run(["--path", str(root), "--title", "Use a queue", "--scope", "api", "--refdate", "2026-09-20"])
    name = created["created"].replace("\\", "/").rsplit("/", 1)[1]

    text = index.read_text(encoding="utf-8")
    row = next(line for line in text.splitlines() if name.split("-")[0] in line)
    assert f"({name})" in row and "Use a queue" in row and "api" in row and "Proposed (2026-09-20)" in row

    approve.run(["--file", created["created"], "--refdate", "2026-09-21"])
    row = next(line for line in index.read_text(encoding="utf-8").splitlines() if name.split("-")[0] in line)
    assert "Accepted (2026-09-21)" in row


def test_the_index_is_ordered_by_number_and_the_same_for_the_same_repository(tmp_path):
    root, index = _repo(tmp_path)
    for title in ("First", "Second", "Third"):
        new.run(["--path", str(root), "--title", title, "--refdate", "2026-09-20"])
    first = index.read_bytes()
    rows = [line for line in first.decode("utf-8").splitlines() if line.startswith("| [")]
    assert [row.split("|")[2].strip() for row in rows] == ["First", "Second", "Third"]

    from adrpy.core.adr_index import regenerate

    regenerate(root, load_repo_config(root / ".adrpy.json"), [])
    assert index.read_bytes() == first  # deterministic: no timestamp


def test_the_index_speaks_the_repository_labels(tmp_path):
    init.run(["--path", str(tmp_path), "--language", "pt-br"])
    config = load_repo_config(tmp_path / ".adrpy.json")
    new.run(["--path", str(tmp_path), "--title", "Primeira", "--refdate", "2026-09-20"])
    text = (tmp_path / config.folderadr / "INDEX.md").read_text(encoding="utf-8")
    header_row = next(line for line in text.splitlines() if line.startswith("| ") and config.headertitlefile in line)
    assert config.headerscope in header_row and config.headertitlestatuscreated in header_row
    assert f"{config.statusnew} (2026-09-20)" in text


def test_a_title_with_link_breaking_characters_is_linked_encoded(tmp_path):
    root, index = _repo(tmp_path)
    created = new.run(["--path", str(root), "--title", "Use (a) queue's", "--refdate", "2026-09-20"])
    name = created["created"].replace("\\", "/").rsplit("/", 1)[1]
    text = index.read_text(encoding="utf-8")
    assert name not in text.split("](")[1]  # the raw name, with its parentheses, would end the link early
    assert "%28" in text and "%29" in text


def test_the_index_is_never_a_decision_nor_a_file_to_report(tmp_path):
    root, index = _repo(tmp_path)
    new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    listed = [entry["filename"] for entry in explore.run(["--path", str(root)])["decisions"]]
    assert all(not entry.endswith("INDEX.md") for entry in listed)
    result = check.run(["--path", str(root)])
    assert result["decisions"] == 1 and not any("INDEX.md" in warning for warning in result["warnings"])


def test_an_index_that_cannot_be_written_is_a_warning_not_a_failure(tmp_path):
    root, index = _repo(tmp_path)
    index.unlink()
    index.mkdir()  # a folder in its place: the write fails

    created = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    assert created["status"] == "Proposed"
    assert any("INDEX.md" in warning for warning in created["warnings"])


def _row(index, name):
    return next((line for line in index.read_text(encoding="utf-8").splitlines() if f"({name}" in line), None)


def _file_name(path):
    return str(path).replace("\\", "/").rsplit("/", 1)[1]


@pytest.mark.real_defaults
def test_every_other_writing_command_keeps_the_index_in_step(tmp_path):
    """reject, undo, version, revise and supersede each rewrite it."""
    from adrpy.cli import reject, revise, supersede, undo, version

    root, index = _repo(tmp_path)
    first = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])["created"]
    reject.run(["--file", first, "--refdate", "2026-09-21"])
    assert "Rejected (2026-09-21)" in _row(index, _file_name(first))
    undo.run(["--file", first])
    assert "Rejected" not in _row(index, _file_name(first))

    approve.run(["--file", first, "--refdate", "2026-09-21"])
    second = version.run(["--file", first, "--refdate", "2026-09-22"])["created"]
    assert _row(index, _file_name(second)) is not None
    approve.run(["--file", second, "--refdate", "2026-09-22"])
    third = revise.run(["--file", second, "--refdate", "2026-09-23"])["created"]
    assert _row(index, _file_name(third)) is not None

    other = new.run(["--path", str(root), "--title", "Other", "--refdate", "2026-09-20"])["created"]
    approve.run(["--file", other, "--refdate", "2026-09-21"])
    successor = supersede.run(["--file", other, "--title", "Successor", "--refdate", "2026-09-24"])["created"]
    assert _row(index, _file_name(successor)) is not None


def test_migrate_keeps_the_index_in_step(tmp_path):
    from adrpy.cli import migrate

    seed = tmp_path / "seed.json"
    init.run(["--path", str(tmp_path)])
    config = json.loads((tmp_path / ".adrpy.json").read_text(encoding="utf-8"))
    config["migrationpattern"] = "N00:04T04"
    seed.write_text(json.dumps(config), encoding="utf-8")
    other = tmp_path / "repo"
    other.mkdir()
    init.run(["--path", str(other), "--seed", str(seed)])
    (other / "doc" / "adr" / "0001UseQueues.md").write_text("# Use queues\n", encoding="utf-8")

    migrate.run(["--path", str(other)])

    assert _row(other / "doc" / "adr" / "INDEX.md", "0001UseQueues.md") is not None
