"""The decisions folder's INDEX.md (ADR0013V01R02): regenerated by every
command that writes a decision, never taken for a decision itself."""
import json

import pytest

from adrpy.cli import approve, check, explore, init, new
from adrpy.core.config import load_repo_config


def _repo(tmp_path):
    init.run(["--path", str(tmp_path)])
    return tmp_path, tmp_path / "doc" / "adr" / "INDEX.md"


def test_init_writes_an_index_with_no_decisions(tmp_path):
    _, index = _repo(tmp_path)
    text = index.read_text(encoding="utf-8")
    assert text.startswith("# ")
    assert "ADR0" not in text


def test_new_and_approve_keep_the_index_in_step(tmp_path):
    root, index = _repo(tmp_path)
    created = new.run(["--path", str(root), "--title", "Use a queue", "--scope", "api", "--refdate", "2026-09-20"])
    name = created["created"].replace("\\", "/").rsplit("/", 1)[1]

    text = index.read_text(encoding="utf-8")
    row = next(line for line in text.splitlines() if name.split("-")[0] in line)
    assert f"({name})" in row and "Use a queue" in row and "api" in row and "Proposed (2026-09-20)" in row

    approve.run(["--file", created["created"], "--refdate", "2026-09-21"])
    row = next(line for line in index.read_text(encoding="utf-8").splitlines() if name.split("-")[0] in line)
    assert "Accepted (2026-09-21)" in row


def test_the_index_is_ordered_by_number_and_the_same_for_the_same_repository(tmp_path):
    root, index = _repo(tmp_path)
    for title in ("First", "Second", "Third"):
        new.run(["--path", str(root), "--title", title, "--refdate", "2026-09-20"])
    first = index.read_bytes()
    rows = [line for line in first.decode("utf-8").splitlines() if line.startswith("| [")]
    assert [row.split("|")[2].strip() for row in rows] == ["First", "Second", "Third"]

    from adrpy.core.adr_index import regenerate

    regenerate(root, load_repo_config(root / ".adrpy.json"), [])
    assert index.read_bytes() == first  # deterministic: no timestamp


def test_the_index_speaks_the_repository_labels(tmp_path):
    init.run(["--path", str(tmp_path), "--language", "pt-br"])
    config = load_repo_config(tmp_path / ".adrpy.json")
    new.run(["--path", str(tmp_path), "--title", "Primeira", "--refdate", "2026-09-20"])
    text = (tmp_path / config.folderadr / "INDEX.md").read_text(encoding="utf-8")
    header_row = next(line for line in text.splitlines() if line.startswith("| ") and config.headertitlefile in line)
    assert config.headerscope in header_row and config.headertitlestatuscreated in header_row
    assert f"{config.statusnew} (2026-09-20)" in text


def test_a_title_with_link_breaking_characters_is_linked_encoded(tmp_path):
    root, index = _repo(tmp_path)
    created = new.run(["--path", str(root), "--title", "Use (a) queue's", "--refdate", "2026-09-20"])
    name = created["created"].replace("\\", "/").rsplit("/", 1)[1]
    text = index.read_text(encoding="utf-8")
    assert name not in text.split("](")[1]  # the raw name, with its parentheses, would end the link early
    assert "%28" in text and "%29" in text


def test_the_index_is_never_a_decision_nor_a_file_to_report(tmp_path):
    root, index = _repo(tmp_path)
    new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    listed = [entry["filename"] for entry in explore.run(["--path", str(root)])["decisions"]]
    assert all(not entry.endswith("INDEX.md") for entry in listed)
    result = check.run(["--path", str(root)])
    assert result["decisions"] == 1 and not any("INDEX.md" in warning for warning in result["warnings"])


def test_an_index_that_cannot_be_written_is_a_warning_not_a_failure(tmp_path):
    root, index = _repo(tmp_path)
    index.unlink()
    index.mkdir()  # a folder in its place: the write fails

    created = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    assert created["status"] == "Proposed"
    assert any("INDEX.md" in warning for warning in created["warnings"])


def _row(index, name):
    return next((line for line in index.read_text(encoding="utf-8").splitlines() if f"({name}" in line), None)


def _file_name(path):
    return str(path).replace("\\", "/").rsplit("/", 1)[1]


@pytest.mark.real_defaults
def test_every_other_writing_command_keeps_the_index_in_step(tmp_path):
    """reject, undo, version, revise and supersede each rewrite it."""
    from adrpy.cli import reject, revise, supersede, undo, version

    root, index = _repo(tmp_path)
    first = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])["created"]
    reject.run(["--file", first, "--refdate", "2026-09-21"])
    assert "Rejected (2026-09-21)" in _row(index, _file_name(first))
    undo.run(["--file", first])
    assert "Rejected" not in _row(index, _file_name(first))

    approve.run(["--file", first, "--refdate", "2026-09-21"])
    second = version.run(["--file", first, "--refdate", "2026-09-22"])["created"]
    assert _row(index, _file_name(second)) is not None
    approve.run(["--file", second, "--refdate", "2026-09-22"])
    third = revise.run(["--file", second, "--refdate", "2026-09-23"])["created"]
    assert _row(index, _file_name(third)) is not None

    other = new.run(["--path", str(root), "--title", "Other", "--refdate", "2026-09-20"])["created"]
    approve.run(["--file", other, "--refdate", "2026-09-21"])
    successor = supersede.run(["--file", other, "--title", "Successor", "--refdate", "2026-09-24"])["created"]
    assert _row(index, _file_name(successor)) is not None


def test_a_users_own_index_is_left_as_it_is_with_a_warning(tmp_path):
    """An INDEX.md adrpy did not generate is the user's: never overwritten,
    whatever its case, and the warning says how to get the generated one."""
    folder = tmp_path / "doc" / "adr"
    folder.mkdir(parents=True)
    notes = folder / "index.md"
    notes.write_text("Hand-written notes.\n", encoding="utf-8")

    result = init.run(["--path", str(tmp_path)])
    created = new.run(["--path", str(tmp_path), "--title", "First", "--refdate", "2026-09-20"])

    assert [p.name for p in folder.iterdir() if p.name.lower() == "index.md"] == ["index.md"]
    assert notes.read_text(encoding="utf-8") == "Hand-written notes.\n"
    for answer in (result, created):
        assert any("was not written by adrpy" in warning for warning in answer["warnings"])


def test_an_error_other_than_oserror_while_indexing_is_a_warning(tmp_path, monkeypatch):
    from adrpy.core import adr_index

    root, _ = _repo(tmp_path)
    monkeypatch.setattr(adr_index, "render", lambda *args: (_ for _ in ()).throw(ValueError("boom")))

    created = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    assert created["status"] == "Proposed"
    assert any("INDEX.md" in warning and "boom" in warning for warning in created["warnings"])


@pytest.mark.skipif(__import__("sys").platform != "win32", reason="a lone surrogate is a valid name on NTFS only")
def test_a_decision_in_a_folder_named_with_a_lone_surrogate_is_indexed(tmp_path):
    root, index = _repo(tmp_path)
    first = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])["created"]
    folder = root / "doc" / "adr" / "s\udc80"
    folder.mkdir()
    moved = folder / _file_name(first)
    __import__("os").replace(first, moved)

    created = new.run(["--path", str(root), "--title", "Second", "--refdate", "2026-09-20"])

    assert created["status"] == "Proposed"
    assert _file_name(moved) in index.read_text(encoding="utf-8")


def test_an_interrupt_while_indexing_leaves_the_decision_written_and_says_so(tmp_path, monkeypatch):
    """Ctrl+C after the decision is written: the result is its success, and
    the index not being updated is a warning."""
    from adrpy.core import adr_index

    root, _ = _repo(tmp_path)

    def interrupted(*args):
        raise KeyboardInterrupt

    monkeypatch.setattr(adr_index, "render", interrupted)
    created = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    assert created["status"] == "Proposed"
    assert any("INDEX.md" in warning and "Ctrl+C" in warning for warning in created["warnings"])


def test_a_config_that_cannot_be_reread_for_the_index_leaves_migrate_s_result(tmp_path, monkeypatch):
    from adrpy.cli import migrate

    seed = tmp_path / "seed.json"
    init.run(["--path", str(tmp_path)])
    config = json.loads((tmp_path / ".adrpy.json").read_text(encoding="utf-8"))
    config["migrationpattern"] = "N00:04T04"
    seed.write_text(json.dumps(config), encoding="utf-8")
    other = tmp_path / "repo"
    other.mkdir()
    init.run(["--path", str(other), "--seed", str(seed)])
    (other / "doc" / "adr" / "0001UseQueues.md").write_text("# Use queues\n", encoding="utf-8")

    def locked(path):
        raise PermissionError(13, "locked", str(path))

    monkeypatch.setattr(migrate, "load_repo_config", locked)
    result = migrate.run(["--path", str(other)])

    assert [entry.replace("\\", "/").rsplit("/", 1)[1] for entry in result["migrated"]] == ["0001UseQueues.md"]
    assert any("index" in warning and "locked" in warning for warning in result["warnings"])


def test_init_says_which_decisions_the_index_leaves_out(tmp_path):
    """init does not validate first: a decision whose header does not parse
    is left out of the index, and the warning says so."""
    root, index = _repo(tmp_path)
    first = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])["created"]
    new.run(["--path", str(root), "--title", "Second", "--refdate", "2026-09-20"])
    path = __import__("pathlib").Path(first)
    path.write_text(path.read_text(encoding="utf-8").replace("|Version|01|", "|Version|zz|"), encoding="utf-8")
    seed = tmp_path / "seed.json"
    seed.write_text((root / ".adrpy.json").read_text(encoding="utf-8"), encoding="utf-8")

    result = init.run(["--path", str(root), "--seed", str(seed)])

    assert _row(index, _file_name(first)) is None
    assert any(_file_name(first) in warning and "not in the decisions index" in warning for warning in result["warnings"])


def test_the_index_warning_does_not_promise_the_next_write_fixes_it(tmp_path):
    root, index = _repo(tmp_path)
    index.unlink()
    index.mkdir()

    created = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    [warning] = [warning for warning in created["warnings"] if "INDEX.md" in warning]
    assert "the next write updates it" not in warning


def test_legacy_names_keep_their_own_link_text(tmp_path):
    """A legacy prefix that holds the separator (ADR-0001-...) must not
    collapse every row's link text to the prefix."""
    from adrpy.cli import migrate

    seed = tmp_path / "seed.json"
    init.run(["--path", str(tmp_path)])
    config = json.loads((tmp_path / ".adrpy.json").read_text(encoding="utf-8"))
    config["migrationpattern"] = "N04:04T09"
    seed.write_text(json.dumps(config), encoding="utf-8")
    other = tmp_path / "repo"
    other.mkdir()
    init.run(["--path", str(other), "--seed", str(seed)])
    for name in ("ADR-0001-use-x.md", "ADR-0002-use-y.md"):
        (other / "doc" / "adr" / name).write_text("# x\n", encoding="utf-8")

    migrate.run(["--path", str(other)])

    rows = [line for line in (other / "doc" / "adr" / "INDEX.md").read_text(encoding="utf-8").splitlines()
            if line.startswith("| [")]
    texts = [row.split("](")[0] for row in rows]
    assert len(set(texts)) == 2


def test_a_config_change_keeps_the_index_in_step(tmp_path):
    """A header label changed by `config` shows in the index at once."""
    from adrpy.cli import config

    root, index = _repo(tmp_path)
    new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    config.run(["--path", str(root), "--headerscope", "Area"])

    header_row = next(line for line in index.read_text(encoding="utf-8").splitlines() if line.startswith("| ") and "Area" in line)
    assert "Scope" not in header_row


def test_a_folderadr_change_writes_the_index_there_and_names_the_one_left_behind(tmp_path):
    from adrpy.cli import config

    root, old_index = _repo(tmp_path)

    result = config.run(["--path", str(root), "--folderadr", "decisions"])

    assert (root / "decisions" / "INDEX.md").is_file()
    assert old_index.is_file()
    assert any(str(old_index) in warning and "previous decisions folder" in warning for warning in result["warnings"])


def test_migrate_keeps_the_index_in_step(tmp_path):
    from adrpy.cli import migrate

    seed = tmp_path / "seed.json"
    init.run(["--path", str(tmp_path)])
    config = json.loads((tmp_path / ".adrpy.json").read_text(encoding="utf-8"))
    config["migrationpattern"] = "N00:04T04"
    seed.write_text(json.dumps(config), encoding="utf-8")
    other = tmp_path / "repo"
    other.mkdir()
    init.run(["--path", str(other), "--seed", str(seed)])
    (other / "doc" / "adr" / "0001UseQueues.md").write_text("# Use queues\n", encoding="utf-8")

    migrate.run(["--path", str(other)])

    assert _row(other / "doc" / "adr" / "INDEX.md", "0001UseQueues.md") is not None


def _unreadable(monkeypatch, name="INDEX.md"):
    """Makes adrpy's read of any file called `name` fail, as a file the user
    may replace but not read does (NTFS deny-read, POSIX mode 000)."""
    from adrpy.core import fs

    real_open = open

    def guarded(path, *args, **kwargs):
        if __import__("pathlib").Path(path).name.lower() == name.lower():
            raise PermissionError(13, "Permission denied", str(path))
        return real_open(path, *args, **kwargs)

    monkeypatch.setattr(fs, "open", guarded, raising=False)


def test_a_users_index_that_cannot_be_read_is_left_as_it_is(tmp_path, monkeypatch):
    """Replacing a file needs no right to read it: one adrpy cannot read is
    the user's, never overwritten, and the warning says so."""
    root, index = _repo(tmp_path)
    index.write_text("# Our own list\n", encoding="utf-8")
    _unreadable(monkeypatch)

    created = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    assert index.read_text(encoding="utf-8") == "# Our own list\n"
    assert any("was not written by adrpy" in warning for warning in created["warnings"])


def test_config_never_calls_an_unreadable_user_file_the_previous_index(tmp_path, monkeypatch):
    from adrpy.cli import config

    root, index = _repo(tmp_path)
    index.write_text("# Our own list\n", encoding="utf-8")
    _unreadable(monkeypatch)

    result = config.run(["--path", str(root), "--folderadr", "decisions"])

    assert index.read_text(encoding="utf-8") == "# Our own list\n"
    assert not any("previous decisions folder" in warning for warning in result["warnings"])


def test_a_user_file_quoting_the_generated_line_is_still_the_users(tmp_path):
    """The mark counts as the start of one of the first lines, as adrpy
    writes it, never as a phrase quoted anywhere in the text."""
    from adrpy.core.adr_index import GENERATED_MARK

    root, index = _repo(tmp_path)
    notes = f"# Our notes\n\nWe keep our own list here; adrpy's page would say \"{GENERATED_MARK}\"\n"
    index.write_text(notes, encoding="utf-8")

    new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    assert index.read_text(encoding="utf-8") == notes


def test_a_generated_index_with_a_bom_is_still_adrpy_s(tmp_path):
    """Positive control: an editor that added a BOM does not turn adrpy's
    own page into a file of the user's."""
    root, index = _repo(tmp_path)
    index.write_bytes(b"\xef\xbb\xbf" + index.read_bytes())

    new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    assert "First" in index.read_text(encoding="utf-8-sig")


@pytest.mark.parametrize("breaker", ["\x0c", " ", "\x85", "\r"])
def test_the_mark_after_a_character_that_is_not_a_line_end_is_still_the_users(tmp_path, breaker):
    """Only the line endings adrpy writes start a line: the mark after a
    form feed or a Unicode separator inside line 1 is quoted text."""
    from adrpy.core.adr_index import GENERATED_MARK

    root, index = _repo(tmp_path)
    notes = f"# Notes about adrpy{breaker}{GENERATED_MARK} is what its page says\n"
    index.write_bytes(notes.encode("utf-8"))

    new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])

    assert index.read_bytes() == notes.encode("utf-8")


@pytest.mark.parametrize("damage", ["conflict", "no-header"])
def test_the_index_names_every_decision_it_leaves_out(tmp_path, damage):
    """Conflict markers in a header, or a decision name with no header at
    all, leave a decision out of the index just as a header that does not
    parse does: the warning names it (config writes the index without
    validating the repository first)."""
    from pathlib import Path

    from adrpy.cli import config

    root, index = _repo(tmp_path)
    new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])
    second = Path(new.run(["--path", str(root), "--title", "Second", "--refdate", "2026-09-20"])["created"])
    text = second.read_text(encoding="utf-8")
    second.write_text(text.replace("|File title md|", "<<<<<<< HEAD\n|File title md|", 1) if damage == "conflict"
                      else "# Second, header removed\n", encoding="utf-8")

    result = config.run(["--path", str(root), "--headerdomain", "Area"])

    assert _row(index, second.name) is None
    assert any(second.name in warning and "not in the decisions index" in warning for warning in result["warnings"])


def test_init_seed_changing_folderadr_names_the_index_left_behind(tmp_path):
    import json

    root, old_index = _repo(tmp_path)
    seed = tmp_path.parent / f"{tmp_path.name}-seed.json"
    data = json.loads((root / ".adrpy.json").read_text(encoding="utf-8"))
    data["folderadr"] = "decisions"
    seed.write_text(json.dumps(data), encoding="utf-8")

    result = init.run(["--path", str(root), "--seed", str(seed)])

    assert (root / "decisions" / "INDEX.md").is_file() and old_index.is_file()
    assert any(str(old_index) in warning and "previous decisions folder" in warning for warning in result["warnings"])


@pytest.mark.skipif(__import__("sys").platform != "win32", reason="a lone surrogate is a valid name on NTFS only")
@pytest.mark.parametrize("surrogate", ["\ud800", "\udfff"])
def test_a_folder_named_with_any_lone_surrogate_does_not_freeze_the_index(tmp_path, surrogate):
    """Outside U+DC80-U+DCFF too, the index is written: its link to that
    folder cannot be exact, but every other row stays true."""
    import os

    root, index = _repo(tmp_path)
    first = new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])["created"]
    folder = root / "doc" / "adr" / f"sub{surrogate}"
    folder.mkdir()
    os.replace(first, folder / _file_name(first))

    second = new.run(["--path", str(root), "--title", "Second", "--refdate", "2026-09-20"])

    assert _row(index, _file_name(second["created"])) is not None
    assert not any("could not be updated" in warning for warning in second["warnings"])


def _blocked_scandir(monkeypatch, blocked):
    import os

    real_scandir = os.scandir

    def flaky_scandir(path="."):
        if os.path.abspath(path) == os.path.abspath(blocked):
            raise PermissionError(13, "Access is denied", str(blocked))
        return real_scandir(path)

    monkeypatch.setattr(os, "scandir", flaky_scandir)


@pytest.mark.parametrize("where", ["root", "subfolder"])
def test_a_folder_that_cannot_be_read_leaves_the_index_as_it_was(tmp_path, monkeypatch, where):
    """A scan that could not read a folder would write an index missing its
    decisions (none at all, for the root): the page stays as it was, and the
    warning names the folder, never as a decision file."""
    from adrpy.cli import config

    root, index = _repo(tmp_path)
    new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])
    blocked = root / "doc" / "adr" if where == "root" else root / "doc" / "adr" / "restricted"
    blocked.mkdir(exist_ok=True)
    before = index.read_bytes()
    _blocked_scandir(monkeypatch, blocked)

    result = config.run(["--path", str(root), "--headerdomain", "Area"])

    assert index.read_bytes() == before
    [warning] = [w for w in result["warnings"] if "INDEX.md" in w or "decisions index" in w]
    assert blocked.name in warning and "decision file" not in warning


def test_the_index_names_what_it_leaves_out_by_its_path_in_the_folder(tmp_path):
    """Two files of one name in two subfolders are two names in the warning."""
    from pathlib import Path

    from adrpy.cli import config

    root, index = _repo(tmp_path)
    created = Path(new.run(["--path", str(root), "--title", "First", "--refdate", "2026-09-20"])["created"])
    broken = created.read_text(encoding="utf-8").replace("|File title md|", "<<<<<<< HEAD\n|File title md|", 1)
    for sub in ("a", "b"):
        (created.parent / sub).mkdir()
        (created.parent / sub / created.name).write_text(broken, encoding="utf-8")

    result = config.run(["--path", str(root), "--headerdomain", "Area"])

    [warning] = [w for w in result["warnings"] if "not in the decisions index" in w]
    assert f"a/{created.name}" in warning and f"b/{created.name}" in warning


@pytest.mark.skipif(__import__("sys").platform != "win32", reason="a lone surrogate is a valid name on NTFS only")
def test_a_legacy_file_named_with_a_lone_surrogate_does_not_freeze_the_index(tmp_path):
    import json
    import os

    from adrpy.cli import migrate

    seed = tmp_path / "seed.json"
    init.run(["--path", str(tmp_path)])
    config = json.loads((tmp_path / ".adrpy.json").read_text(encoding="utf-8"))
    config["migrationpattern"] = "N00:04T04"
    seed.write_text(json.dumps(config), encoding="utf-8")
    repo = tmp_path / "repo"
    repo.mkdir()
    init.run(["--path", str(repo), "--seed", str(seed)])
    folder = repo / "doc" / "adr"
    (folder / "0002Plain.md").write_text("# Plain\n", encoding="utf-8")
    migrate.run(["--path", str(repo)])
    os.replace(folder / "0002Plain.md", folder / "0002Pl\ud800ain.md")

    created = new.run(["--path", str(repo), "--title", "Third", "--refdate", "2026-09-20"])

    assert _row(folder / "INDEX.md", _file_name(created["created"])) is not None
