"""Regenerates doc/decision-log/INDEX.md from the entry files themselves.

Per the decision-log skill: the index is always generated, never hand-
maintained prose. Run this after adding, never after editing, an entry
(entries are never edited in place -- a correction is a new `retraction`
entry instead).

Usage: python scripts/generate_decision_log_index.py
"""

import re
from pathlib import Path

DECISION_LOG_DIR = Path(__file__).resolve().parent.parent / "doc" / "decision-log"
INDEX_PATH = DECISION_LOG_DIR / "INDEX.md"

_FRONT_SEVERITY_RE = re.compile(
    r"^\*\*Front:\*\*\s*(.+?)\s*\|\s*\*\*Severity:\*\*\s*(.+?)"
    r"(?:\s*\|\s*\*\*Resolution:\*\*\s*(.+?))?\s*$"
)


def _parse_entry(path):
    date, classification, scope, _slug = path.stem.split("--", 3)
    lines = path.read_text(encoding="utf-8").splitlines()
    heading = lines[0].lstrip("#").strip()
    front, severity, resolution = "", "", ""
    for line in lines[1:5]:
        match = _FRONT_SEVERITY_RE.match(line)
        if match:
            front, severity, resolution = match.group(1), match.group(2), match.group(3) or ""
            break
    return {
        "path": path.name,
        "classification": classification,
        "date": date,
        "scope": scope,
        "summary": heading,
        "front": front,
        "severity": severity,
        "resolution": resolution,
    }


def generate():
    entries = [
        _parse_entry(path)
        for path in sorted(DECISION_LOG_DIR.glob("*.md"))
        if path.name != INDEX_PATH.name
    ]
    entries.sort(key=lambda entry: (entry["date"], entry["classification"], entry["scope"]))

    lines = [
        "# Decision log index",
        "",
        "Generated by `scripts/generate_decision_log_index.py` -- do not edit by hand.",
        "",
        "## How entries are named",
        "",
        "Every file follows `{ISO date}--{classification}--{scope}--{slug}.md` "
        "(date first so a raw directory listing already sorts chronologically, "
        "matching this generated index's own sort order):",
        "",
        "- **date** -- ISO date the entry was written, not necessarily when the "
        "underlying event happened.",
        "- **classification** -- a closed vocabulary: `audit-finding` (a bug found "
        "and fixed, or a review pass's closure claim), `retraction` (a prior verdict "
        "or decision that didn't hold), `doc-drift` (a durable doc describing "
        "something that stopped being true), `accepted-divergence` (a confirmed "
        "difference from some external reference, not an architecture change), "
        "`scope-note` (a clarification of an existing decision's boundary), "
        "`deferred` (postponed, with a named reopening condition), `risk-accepted` "
        "(a known gap left unfixed on purpose, no reopening condition), "
        "`investigation` (a suspicion checked and found not to hold), or "
        "`process-exception` (a one-off deviation from standing process).",
        "- **scope** -- the module/command/concern the entry is about, reusing the "
        "project's own vocabulary (e.g. `lock`, `config`, `cli`).",
        "- **slug** -- a few kebab-case words identifying this specific entry; what "
        "actually guarantees the filename is unique, since classification+date+scope "
        "alone commonly repeat.",
        "",
        "For `audit-finding` entries specifically, the three extra columns below come "
        "from a structured line inside the entry itself (`**Front:** ... | "
        "**Severity:** ... | **Resolution:** ...`), used by the `pre-release-audit` "
        "skill's calibration step -- blank for every other classification, which "
        "doesn't carry that line:",
        "",
        "- **Front** -- which review angle found it, and in which round.",
        "- **Severity** -- Low / Medium / High.",
        "- **Resolution** -- `Direct` (followed an already-established pattern, no "
        "design choice needed), `Escalated` (a real trade-off, presented as options "
        "and chosen by the project owner before implementation), or `Retraction` "
        "(reverses a previously confirmed decision that didn't hold).",
        "",
        "| Date | Classification | Scope | Front | Severity | Resolution | Summary | File |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        lines.append(
            f"| {entry['date']} | {entry['classification']} | {entry['scope']} "
            f"| {entry['front']} | {entry['severity']} | {entry['resolution']} "
            f"| {entry['summary']} | [{entry['path']}]({entry['path']}) |"
        )
    lines.append("")

    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return len(entries)


if __name__ == "__main__":
    count = generate()
    print(f"Regenerated {INDEX_PATH} with {count} entries.")
