"""Regenerates doc/decision-log/INDEX.md from the entry files themselves.

Per the decision-log skill: the index is always generated, never hand-
maintained prose. Run this after adding, never after editing, an entry
(entries are never edited in place -- a correction is a new `retraction`
entry instead).

Usage: python scripts/generate_decision_log_index.py
"""

import re
from pathlib import Path

DECISION_LOG_DIR = Path(__file__).resolve().parent.parent / "doc" / "decision-log"
INDEX_PATH = DECISION_LOG_DIR / "INDEX.md"
# CYCLES.md is the one deliberate hand-written exception (see the
# decision-log skill's "Cycles" section) -- not an entry, never parsed.
_NON_ENTRY_FILES = {INDEX_PATH.name, "CYCLES.md"}

_FRONT_SEVERITY_RE = re.compile(
    r"^\*\*Front:\*\*\s*(.+?)\s*\|\s*\*\*Severity:\*\*\s*(.+?)"
    r"(?:\s*\|\s*\*\*Resolution:\*\*\s*(.+?))?"
    r"(?:\s*\|\s*\*\*Round:\*\*\s*(.+?))?\s*$"
)
_REOPEN_WHEN_RE = re.compile(r"^\*\*Reopen-when:\*\*\s*(.+?)\s*$")


def _parse_entry(path):
    date, classification, scope, _slug = path.stem.split("--", 3)
    lines = path.read_text(encoding="utf-8").splitlines()
    heading = lines[0].lstrip("#").strip()
    front, severity, resolution, round_, reopen_when = "", "", "", "", ""
    for line in lines[1:5]:
        match = _FRONT_SEVERITY_RE.match(line)
        if match:
            front, severity = match.group(1), match.group(2)
            resolution, round_ = match.group(3) or "", match.group(4) or ""
            break
        match = _REOPEN_WHEN_RE.match(line)
        if match:
            reopen_when = match.group(1)
            break
    return {
        "path": path.name,
        "classification": classification,
        "date": date,
        "scope": scope,
        "summary": heading,
        "front": front,
        "severity": severity,
        "resolution": resolution,
        "round": round_,
        "reopen_when": reopen_when,
    }


def generate():
    entries = [
        _parse_entry(path)
        for path in sorted(DECISION_LOG_DIR.glob("*.md"))
        if path.name not in _NON_ENTRY_FILES
    ]
    entries.sort(key=lambda entry: (entry["date"], entry["classification"], entry["scope"]))

    lines = [
        "# Decision log index",
        "",
        "Generated by `scripts/generate_decision_log_index.py` -- do not edit by hand.",
        "",
        "## How entries are named",
        "",
        "Every file follows `{ISO date}--{classification}--{scope}--{slug}.md` "
        "(date first so a raw directory listing already sorts chronologically, "
        "matching this generated index's own sort order):",
        "",
        "- **date** -- ISO date the entry was written, not necessarily when the "
        "underlying event happened.",
        "- **classification** -- a closed vocabulary: `audit-finding` (a bug found "
        "and fixed, or a review pass's closure claim), `retraction` (a prior verdict "
        "or decision that didn't hold), `doc-drift` (a durable doc describing "
        "something that stopped being true), `accepted-divergence` (a confirmed "
        "difference from some external reference, not an architecture change), "
        "`scope-note` (a clarification of an existing decision's boundary), "
        "`deferred` (postponed, with a named reopening condition), `risk-accepted` "
        "(a known gap left unfixed on purpose, no reopening condition), "
        "`investigation` (a suspicion checked and found not to hold), or "
        "`process-exception` (a one-off deviation from standing process).",
        "- **scope** -- the module/command/concern the entry is about, reusing the "
        "project's own vocabulary (e.g. `lock`, `config`, `cli`).",
        "- **slug** -- a few kebab-case words identifying this specific entry; what "
        "actually guarantees the filename is unique, since classification+date+scope "
        "alone commonly repeat.",
        "",
        "For `audit-finding`/`doc-drift` entries specifically, the four extra columns "
        "below come from a structured line inside the entry itself (`**Front:** ... | "
        "**Severity:** ... | **Resolution:** ... | **Round:** ...`), used by the "
        "`pre-release-audit` skill's calibration step -- blank for every other "
        "classification, which doesn't carry that line:",
        "",
        "- **Front** -- which review angle found it (free text -- may still mention "
        "the round narratively, but **Round** below is the authoritative, "
        "mechanically-parseable value).",
        "- **Severity** -- Low / Medium / High.",
        "- **Resolution** -- `Direct` (followed an already-established pattern, no "
        "design choice needed), `Escalated` (a real trade-off, presented as options "
        "and chosen by the project owner before implementation), or `Retraction` "
        "(reverses a previously confirmed decision that didn't hold).",
        "- **Round** -- a single, project-wide, ever-increasing integer identifying "
        "the pre-release-audit round this entry belongs to. Never resets. A "
        "human-friendly **Cycle** name grouping a range of rounds, when one is "
        "warranted, lives separately in `doc/decision-log/CYCLES.md` -- never "
        "repeated on individual entries, and only ever assigned in hindsight once a "
        "cycle's own boundary is visible (see that file for the naming rule).",
        "",
        "`deferred` entries carry their own, different structured line instead -- "
        "`**Reopen-when:** ...` -- the reopening condition every `deferred` entry "
        "already has to name, structured so it can be checked mechanically without "
        "re-reading each entry's own prose.",
        "",
        "| Date | Classification | Scope | Front | Severity | Resolution | Round | Reopen-when | Summary | File |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        lines.append(
            f"| {entry['date']} | {entry['classification']} | {entry['scope']} "
            f"| {entry['front']} | {entry['severity']} | {entry['resolution']} | {entry['round']} "
            f"| {entry['reopen_when']} | {entry['summary']} | [{entry['path']}]({entry['path']}) |"
        )
    lines.append("")

    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return len(entries)


if __name__ == "__main__":
    count = generate()
    print(f"Regenerated {INDEX_PATH} with {count} entries.")
