"""The decisions folder's INDEX.md (ADR0013V01R02): one table of every
decision, regenerated at the end of every command that writes one. Built
from the same snapshot `check` reads, with the repository's own header
labels, and deterministic -- an unchanged repository rewrites it byte for
byte."""

from pathlib import Path
from urllib.parse import quote

from adrpy.core.atomic_write import atomic_write_text
from adrpy.core.consistency import check_repository
from adrpy.core.errors import CommandError, FailureCodes
from adrpy.core.fs import scan_tree, written_by_someone_else
from adrpy.core.header import _STATUS_CONFIG_FIELD
from adrpy.core.output import explain

INDEX_NAME = "INDEX.md"
# The line that tells the generated index from a file of the user's.
GENERATED_MARK = "Generated by adrpy at every write -- do not edit by hand."


def _status(config, status, day, suffix=""):
    if status is None:
        return ""
    label = getattr(config, _STATUS_CONFIG_FIELD[status])
    return f"{label} ({day.isoformat()}){suffix}" if day else f"{label}{suffix}"


def _link_text(decision, config):
    """The name's identity part; a legacy name keeps all of it, since its
    prefix may hold the separator (`ADR-0001-...`)."""
    name = Path(decision.path).name
    return Path(name).stem if decision.scheme == "legacy" else name.split(config.separator, 1)[0]


def render(folder, config, warnings):
    """INDEX.md's text for the decisions under `folder`. A decision whose
    header does not parse is left out, and `warnings` names it: only `init`
    gets here without validating first. One with no header yet (before
    migrate) is left out silently, as its own warnings already say."""
    snapshot, errors = check_repository(folder, config, scan_tree(folder))
    decisions = sorted((d for d in snapshot.decisions if d.header is not None and d.header.is_valid),
                       key=lambda d: (d.name.number, d.name.version, d.name.revision or 0))
    left_out = sorted(Path(error["file"]).name for error in errors if error["code"] == FailureCodes.INVALID_HEADER)
    if left_out:
        warnings.append(
            f"{len(left_out)} decision file(s) are not in the decisions index, because their header does not "
            f"parse: {', '.join(left_out)}. `adrpy check` says what each one needs."
        )
    columns = [config.prefix or "#", config.headertitlefile, config.headerscope, config.headerdomain,
               config.headertitlestatuscreated, config.headertitlestatuschanged, config.headertitlestatussuperseded]
    lines = [
        f"# {config.prefix or 'Decisions'}",
        "",
        GENERATED_MARK,
        "",
        "| " + " | ".join(columns) + " |",
        "|" + "|".join("--" for _ in columns) + "|",
    ]
    for decision in decisions:
        header = decision.header
        relative = Path(decision.path).relative_to(folder).as_posix()
        successor = f" : {header.superseded_by_file}" if header.superseded_by_file else ""
        cells = [
            # surrogateescape: a folder name NTFS allows but UTF-8 cannot hold still gets a link.
            f"[{_link_text(decision, config)}]({quote(relative, safe='/-_.,;', errors='surrogateescape')})",
            header.title,
            header.scope,
            header.domain,
            _status(config, header.status_create, header.date_create),
            _status(config, header.status_update, header.date_update),
            _status(config, header.status_change, header.date_change, successor),
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def regenerate(root, config, warnings):
    """Rewrites `<root>/<folderadr>/INDEX.md`. `config` may instead be a
    callable that loads it. Nothing here is raised, not even Ctrl+C: what
    the command wrote is written, so any failure is added to `warnings`.
    An INDEX.md without GENERATED_MARK is the user's and is left as it is."""
    path = INDEX_NAME
    try:
        if callable(config):
            config = config()
        folder = Path(root) / config.folderadr
        path = folder / INDEX_NAME
        if written_by_someone_else(path, GENERATED_MARK):
            warnings.append(
                f"{path} was not written by adrpy, so it is left as it is and the decisions index is not "
                "written: rename or move that file to have the index."
            )
            return
        atomic_write_text(path, render(folder, config, warnings))
    except KeyboardInterrupt:
        warnings.append(f"The decisions index ({path}) was not updated: interrupted (Ctrl+C). "
                        "What the command wrote stays written.")
    except Exception as error:
        detail = error.detail if isinstance(error, CommandError) else explain(error)
        warnings.append(f"The decisions index ({path}) could not be updated: {detail} -- "
                        "the next command that writes a decision tries again.")
