"""The decisions folder's INDEX.md (ADR0013V01R02): one table of every
decision, regenerated at the end of every command that writes one. Built
from the same snapshot `check` reads, with the repository's own header
labels, and deterministic -- an unchanged repository rewrites it byte for
byte."""

from pathlib import Path
from urllib.parse import quote

from adrpy.core.atomic_write import atomic_write_text
from adrpy.core.consistency import check_repository
from adrpy.core.errors import CommandError, FailureCodes
from adrpy.core.fs import scan_tree, written_by_someone_else
from adrpy.core.header import _STATUS_CONFIG_FIELD
from adrpy.core.output import explain

INDEX_NAME = "INDEX.md"
# The line that tells the generated index from a file of the user's.
GENERATED_MARK = "Generated by adrpy at every write -- do not edit by hand."


def _status(config, status, day, suffix=""):
    if status is None:
        return ""
    label = getattr(config, _STATUS_CONFIG_FIELD[status])
    return f"{label} ({day.isoformat()}){suffix}" if day else f"{label}{suffix}"


def _link_text(decision, config):
    """The name's identity part; a legacy name keeps all of it, since its
    prefix may hold the separator (`ADR-0001-...`)."""
    name = Path(decision.path).name
    text = Path(name).stem if decision.scheme == "legacy" else name.split(config.separator, 1)[0]
    # A lone surrogate (valid on NTFS) cannot be written as UTF-8: shown as U+FFFD.
    return text.encode("utf-8", "surrogatepass").decode("utf-8", "replace")


def _in_folder(path, folder):
    relative = Path(path).relative_to(folder).as_posix() if Path(path).is_relative_to(folder) else str(path)
    return str(path) if relative == "." else relative


def render(folder, config, warnings):
    """INDEX.md's text for the decisions under `folder`. Every decision it
    leaves out (a header that does not parse, conflict markers, a file that
    cannot be read, a decision name with no header) is named in `warnings`,
    by its path in the folder: `init` and `config` write the index without
    validating first. A legacy name with no header yet (before migrate) is
    left out silently, as its own warnings already say. A folder the scan
    could not read raises instead: the page would miss its decisions."""
    scan = scan_tree(folder)
    if scan.unreadable:
        raise CommandError(
            FailureCodes.SCAN_INCOMPLETE,
            f"{len(scan.unreadable)} folder(s) could not be read, so the page would miss their decisions; it is "
            f"left as it was: {', '.join(sorted(_in_folder(path, folder) for path in scan.unreadable))}",
        )
    snapshot, errors = check_repository(folder, config, scan)
    decisions = sorted((d for d in snapshot.decisions if d.header is not None and d.header.is_valid),
                       key=lambda d: (d.name.number, d.name.version, d.name.revision or 0))
    legacy = {str(d.path) for d in snapshot.decisions if d.scheme == "legacy"}
    unlisted = (FailureCodes.INVALID_HEADER, FailureCodes.MERGE_CONFLICT_MARKERS, FailureCodes.SCAN_INCOMPLETE)
    left_out = sorted(_in_folder(error["file"], folder) for error in errors
                      if error["code"] in unlisted or (error["code"] == FailureCodes.NO_HEADER and error["file"] not in legacy))
    if left_out:
        warnings.append(
            f"{len(left_out)} decision file(s) are not in the decisions index, because their header does not "
            f"parse or could not be read: {', '.join(left_out)}. `adrpy check` says what each one needs."
        )
    columns = [config.prefix or "#", config.headertitlefile, config.headerscope, config.headerdomain,
               config.headertitlestatuscreated, config.headertitlestatuschanged, config.headertitlestatussuperseded]
    lines = [
        f"# {config.prefix or 'Decisions'}",
        "",
        GENERATED_MARK,
        "",
        "| " + " | ".join(columns) + " |",
        "|" + "|".join("--" for _ in columns) + "|",
    ]
    for decision in decisions:
        header = decision.header
        relative = Path(decision.path).relative_to(folder).as_posix()
        successor = f" : {header.superseded_by_file}" if header.superseded_by_file else ""
        cells = [
            # surrogatepass: a folder name NTFS allows but UTF-8 cannot hold (a lone surrogate) must
            # not stop the whole page; that one link cannot be exact.
            f"[{_link_text(decision, config)}]({quote(relative, safe='/-_.,;', errors='surrogatepass')})",
            header.title,
            header.scope,
            header.domain,
            _status(config, header.status_create, header.date_create),
            _status(config, header.status_update, header.date_update),
            _status(config, header.status_change, header.date_change, successor),
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def previous_index_warning(old_folder, new_folder, warnings):
    """After a folderadr change, names the generated index the previous
    folder still holds (never deleted: it is the user's call)."""
    old_index = Path(old_folder) / INDEX_NAME
    if Path(new_folder) != Path(old_folder) and old_index.is_file() and not written_by_someone_else(old_index, GENERATED_MARK):
        warnings.append(f"{old_index} is the index of the previous decisions folder: delete it if it is no longer needed.")


def regenerate(root, config, warnings):
    """Rewrites `<root>/<folderadr>/INDEX.md`. `config` may instead be a
    callable that loads it. Nothing here is raised, not even Ctrl+C: what
    the command wrote is written, so any failure is added to `warnings`.
    An INDEX.md without GENERATED_MARK is the user's and is left as it is."""
    path = INDEX_NAME
    try:
        if callable(config):
            config = config()
        folder = Path(root) / config.folderadr
        path = folder / INDEX_NAME
        if written_by_someone_else(path, GENERATED_MARK):
            warnings.append(
                f"{path} was not written by adrpy (or cannot be read), so it is left as it is and the decisions index is not "
                "written: rename or move that file to have the index."
            )
            return
        atomic_write_text(path, render(folder, config, warnings))
    except KeyboardInterrupt:
        warnings.append(f"The decisions index ({path}) was not updated: interrupted (Ctrl+C). "
                        "What the command wrote stays written.")
    except Exception as error:
        detail = error.detail if isinstance(error, CommandError) else explain(error)
        warnings.append(f"The decisions index ({path}) could not be updated: {detail} -- "
                        "the next command that writes a decision tries again.")
